#Numpy

numpy es una libreria de python para computación científica y manejo eficiente de datos numéricos mediante arrays multidimensionales.

##Ventajas grandes de numpy
- es mucho más ráoido que otras librerias
- es compatible con muchas bibliotecas
  - Visualización: seaborn, matplotlib
  - Ciencia de datos: pandas, scikit-learn

In [4]:
import random
salary_list = [random.randint(50000,100000) for i in range(1000000)]

##Usaremos la librería de statistics y %%timeit para comparar la ejecución de ambas librerias

In [6]:
import statistics

In [7]:
%%timeit

statistics.mean(salary_list)

279 ms ± 12.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [8]:
import numpy as np

In [9]:
%%timeit

np.mean(salary_list)

67.7 ms ± 21.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Numpy es mucho más rápido para ejecutar el mismo cálculo, a pesar de ser milisegundos, cuando se trabaja con miles de millones de datos un trabajo

In [10]:
my_array = np.array([1,2,3,4,5])

In [13]:
my_array.mean()

np.float64(3.0)

In [21]:
job_titles = np.array(["Software dev","Data eng","Data Analyst","Data Scientist","ML engineer"])

base_salaries =  np.array([20000, 30000, 10000, 45000, 40000])

bonus_rates =  np.array([.14, .12, .11, .15, .16])

In [22]:
total_salaries = base_salaries * (1 + bonus_rates)

total_salaries

array([22800., 33600., 11100., 51750., 46400.])

In [23]:
np.mean(total_salaries)

np.float64(33130.0)

Podemos usar nan para valores que no tenemos. Se llama con np.nan

In [24]:
job_titles = np.array(["Software dev","Data eng","Data Analyst","Data Scientist","ML engineer", "AI engineer"])

base_salaries =  np.array([20000, 30000, 10000, 45000, 40000, np.nan])

bonus_rates =  np.array([.14, .12, .11, .15, .16, np.nan])

In [25]:
total_salaries = base_salaries * (1 + bonus_rates)

total_salaries

array([22800., 33600., 11100., 51750., 46400.,    nan])

In [27]:
# El metodo mean no funciona con valores nan, para ello debemos utilizar nanmean
#np.mean(total_salaries)

np.nanmean(total_salaries)

#El resultado debe ser igual al anterior ya que no se cuentan los valores nan en el proceso

np.float64(33130.0)

# Pandas

Pandas sirve para trabajar con datos de manera eficiente y flexible en Python.

- Limpieza y tratamiento de datos: Ideal para preparar datos eliminando valores nulos, duplicados o inconsistencias.

- Análisis exploratorio de datos (EDA): Facilita la visualización y el análisis inicial de los datos para identificar patrones o tendencias.

- Soporte para Machine Learning: Sirve como base para preparar datos antes de entrenar modelos.

- Consultas en bases de datos: Permite realizar consultas y transformaciones en datos relacionales.

- Visualización de datos: Se integra con bibliotecas como Matplotlib y Seaborn para crear gráficos.

- Lectura y escritura de archivos: Compatible con formatos como CSV, Excel, JSON, SQL, entre otros.

In [28]:
import pandas as pd
src_path = "/content/sample_data/california_housing_test.csv"
df = pd.read_csv(src_path)
#df = pd.read_excel("src_path")

df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [29]:
type(df)

pandas.core.frame.DataFrame

In [30]:
df.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0

###Para acceder a las columnas:

hay dos formas, con un . o con [] y ""

In [33]:
df['total_bedrooms']

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [34]:
df.total_bedrooms

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

Podemos seleccionar una o varias filas

In [35]:
df.total_bedrooms[0]

np.float64(661.0)

In [39]:
df.total_bedrooms[1:10]

1    310.0
2    507.0
3     15.0
4    244.0
5    213.0
6    225.0
7    471.0
8    617.0
9    632.0
Name: total_bedrooms, dtype: float64

In [40]:
from datasets import load_dataset

ds = load_dataset("lukebarousse/data_jobs")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/3.25k [00:00<?, ?B/s]

data_jobs.csv: reconstructing file:   0%|          |  0.00B /  231MB

data_jobs.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

Aqui tenemos un dataset, pero ocupamos cambiarlo a pandas

In [44]:
df = ds['train'].to_pandas()

In [45]:
df.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."