# Pandas Inspection

In [109]:
from datasets import load_dataset

ds = load_dataset("lukebarousse/data_jobs")

In [110]:
print(ds.keys())
print(ds["train"].column_names)

dict_keys(['train'])
['job_title_short', 'job_title', 'job_location', 'job_via', 'job_schedule_type', 'job_work_from_home', 'search_location', 'job_posted_date', 'job_no_degree_mention', 'job_health_insurance', 'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg', 'company_name', 'job_skills', 'job_type_skills']

In [111]:
import pandas as pd

df = ds["train"].to_pandas()

#Head, Tail y columns

Estos comandos nos sirven para ver el contenido de nuestro dataset: el principio, el final y las columnas respectivamente

In [112]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

Los últimos dos elementos, en ocasiones es útil mirar la cola del data set para ver que se ha importado corretamente. Por ejemplo, podemos revisar que

In [113]:
df.tail(2)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [114]:
df.columns

Index(['job_title_short', 'job_title', 'job_location', 'job_via',
       'job_schedule_type', 'job_work_from_home', 'search_location',
       'job_posted_date', 'job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'company_name', 'job_skills', 'job_type_skills'],
      dtype='object')

###shape

shape nos dice las filas y columnas del dataset.
size es una alternativa menos interpetable, sin embargo, existe

Aqui hago uso de dropna para eliminar valores nulos de el dataset, aunque esto es algo más avanzado

In [115]:
#dfdropna es un mal nombre para el dataset, solo lo dejo de ejemplo
dfdropna = df.dropna(subset=["salary_year_avg"])

print(dfdropna[["job_title_short", "salary_year_avg"]].head())

print()

print("df:",df.shape) # total de elementos
print("dfdropna:",dfdropna.shape)

    job_title_short  salary_year_avg
28   Data Scientist         109500.0
77    Data Engineer         140000.0
92    Data Engineer         120000.0
100  Data Scientist         228222.0
109    Data Analyst          89000.0

df: (785741, 17)
dfdropna: (22003, 17)

Un equivalente de menos espacio de la celda anterior es el siuiente, solo que nos deja sin el resto de la información

In [116]:
dfdropna = df[["job_title_short", "salary_year_avg"]].dropna(subset=["salary_year_avg"])

dfdropna.head()

print("dfdropna:",dfdropna.shape)
#También existe size que nos da el total de elementos contando nan, pero es menos claro que shape
dfdropna.size

dfdropna: (22003, 2)

44006

In [117]:
#Por el momento quiero el dataset completo asi que lo vuelvo a copiar. Es buena práctica el usar copy()
df_salario_limpio = df.dropna(subset=["salary_year_avg"]).copy()
df_salario_limpio["salary_month_avg"] = (df_salario_limpio["salary_year_avg"]/12)

df_salario_limpio[["salary_year_avg","salary_month_avg"]].head(10)

     salary_year_avg  salary_month_avg
28          109500.0       9125.000000
77          140000.0      11666.666667
92          120000.0      10000.000000
100         228222.0      19018.500000
109          89000.0       7416.666667
116         114000.0       9500.000000
146         129500.0      10791.666667
180          90250.0       7520.833333
212         157500.0      13125.000000
257         103128.0       8594.000000

In [118]:
df_salario_limpio.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,salary_month_avg
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd...",9125.000000
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac...",11666.666667
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}",10000.000000
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr...",19018.500000
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro...",7416.666667

###Iloc

In [119]:
# iloc se usa para encontrar elementos, usa (filas, columnas) y puede usarse el slicing
# esto es el equivalente al  head()
df.iloc[:5,:]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

Ejemplo, quiero el elemento 100 (fila 101)

In [120]:
# El índice original puede tener saltos porque usamos dropna()
# y las filas eliminadas conservaban sus índices originales.

# iloc ignora las etiquetas del índice y utiliza posiciones.
# La numeración de posiciones comienza en 0:
# si tenemos 5 filas, iloc[4, :] selecciona la 5ta fila.
df_salario_limpio.iloc[100, :]

job_title_short                                             Data Scientist
job_title                                         Marketing Data Scientist
job_location                                                      Anywhere
job_via                                                         via Indeed
job_schedule_type                                               Contractor
job_work_from_home                                                    True
search_location                                                    Georgia
job_posted_date                                        2023-01-01 14:17:40
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                  United States
salary_rate                                                           year
salary_year_avg                                                   113000.0
salary_hour_avg                                                        NaN
company_name                                                Stefanini, Inc
job_skills               ['python', 'r', 'azure', 'databricks', 'aws', ...
job_type_skills          {'analyst_tools': ['tableau', 'power bi'], 'cl...
salary_month_avg                                               9416.666667
Name: 2862, dtype: object

Con el dataset original:

In [121]:
df.iloc[100, :]

job_title_short                                             Data Scientist
job_title                          Data Scientist, Risk Data Mining - USDS
job_location                                             Mountain View, CA
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                  California, United States
job_posted_date                                        2023-07-31 13:01:18
job_no_degree_mention                                                False
job_health_insurance                                                  True
job_country                                                  United States
salary_rate                                                           year
salary_year_avg                                                   228222.0
salary_hour_avg                                                        NaN
company_name                                                        TikTok
job_skills                               ['sql', 'r', 'python', 'express']
job_type_skills          {'programming': ['sql', 'r', 'python'], 'webfr...
Name: 100, dtype: object

###.info()

info nos sirve para ver la integridad del dataset, es muy útil.

Puede ayudarnos a identificar columnas no útiles o que tengan errores como varios tipos de datatypes en una columna, o un datatype erroneo (como una fecha en formato string).

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [123]:
df_salario_limpio.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22003 entries, 28 to 785692
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        22003 non-null  object
 1   job_title              22003 non-null  object
 2   job_location           21723 non-null  object
 3   job_via                22003 non-null  object
 4   job_schedule_type      21987 non-null  object
 5   job_work_from_home     22003 non-null  bool
 6   search_location        22003 non-null  object
 7   job_posted_date        22003 non-null  object
 8   job_no_degree_mention  22003 non-null  bool
 9   job_health_insurance   22003 non-null  bool
 10  job_country            22003 non-null  object
 11  salary_rate            22003 non-null  object
 12  salary_year_avg        22003 non-null  float64
 13  salary_hour_avg        0 non-null      float64
 14  company_name           22003 non-null  object
 15  job_skills             20170 non-null  object
 16  job_type_skills        20170 non-null  object
 17  salary_month_avg       22003 non-null  float64
dtypes: bool(3), float64(3), object(12)
memory usage: 3.3+ MB

# describe()

describe es otro método extremadamente útil ya que nos ayuda a detectar problemas como

In [124]:
df_salario_limpio.describe()

       salary_year_avg  salary_hour_avg  salary_month_avg
count     22003.000000              0.0      22003.000000
mean     123286.274072              NaN      10273.856173
std       48312.449482              NaN       4026.037457
min       15000.000000              NaN       1250.000000
25%       90000.000000              NaN       7500.000000
50%      115000.000000              NaN       9583.333333
75%      150000.000000              NaN      12500.000000
max      960000.000000              NaN      80000.000000

Se muestran únicamente las variables numéricas, en este ejemplo solo 3 columnas son numéricas.

###unique()

unique nos sirve para identificar los diferentes valores de una columna. Con estos podemos detectar por ejemplo si una columna solo tiene 1 valor.

In [125]:
job_titles = df_salario_limpio.job_title_short.unique()
print(job_titles)

['Data Scientist' 'Data Engineer' 'Data Analyst' 'Senior Data Engineer'
 'Business Analyst' 'Software Engineer' 'Senior Data Analyst'
 'Machine Learning Engineer' 'Senior Data Scientist' 'Cloud Engineer']

In [126]:
skills = df_salario_limpio.job_skills.unique()
print(skills)
#NOTA: en este ejemplo las listas contienen combinaciones de skills, por ello se consideran valores distintos y se repiten elementos como python

["['gdpr', 'excel']"
 "['mongodb', 'mongodb', 'python', 'r', 'sql', 'mysql', 'mariadb', 'oracle', 'spark', 'tableau', 'kubernetes']"
 "['sql', 'python']" ...
 "['go', 'python', 'r', 'sql', 'oracle', 'windows', 'alteryx', 'power bi', 'tableau', 'qlik']"
 "['python', 'hadoop', 'spark', 'airflow', 'kubernetes']"
 "['python', 'matlab', 'r']"]

Se puede hacer una versión mejor de esto, estoy utilizando ast para corregir las listas que entraron como strings

In [127]:
import ast

skills = df_salario_limpio.job_skills.unique()
skillset_set = set()

for skill_list in skills:
    if skill_list is not None:
        skill_list = ast.literal_eval(skill_list)

        for skill in skill_list:
            skillset_set.add(skill)

print(sorted(skillset_set))

['airflow', 'airtable', 'alteryx', 'angular', 'angular.js', 'ansible', 'apl', 'arch', 'asana', 'asp.net', 'asp.net core', 'assembly', 'atlassian', 'aurora', 'aws', 'azure', 'bash', 'bigquery', 'bitbucket', 'blazor', 'c', 'c#', 'c++', 'cassandra', 'centos', 'chainer', 'chef', 'clickup', 'clojure', 'cobol', 'codecommit', 'cognos', 'colocation', 'confluence', 'cordova', 'couchbase', 'couchdb', 'crystal', 'css', 'dart', 'databricks', 'datarobot', 'dax', 'db2', 'debian', 'delphi', 'digitalocean', 'django', 'docker', 'dplyr', 'drupal', 'dynamodb', 'elasticsearch', 'electron', 'elixir', 'erlang', 'excel', 'express', 'fastapi', 'fastify', 'firebase', 'firestore', 'flask', 'flow', 'flutter', 'fortran', 'gatsby', 'gcp', 'gdpr', 'ggplot2', 'git', 'github', 'gitlab', 'go', 'golang', 'graphql', 'groovy', 'hadoop', 'haskell', 'heroku', 'homebrew', 'html', 'hugging face', 'ibm cloud', 'java', 'javascript', 'jenkins', 'jira', 'jquery', 'julia', 'jupyter', 'kafka', 'kali', 'keras', 'kotlin', 'kubernetes', 'laravel', 'linux', 'lisp', 'looker', 'lua', 'macos', 'mariadb', 'matlab', 'matplotlib', 'microsoft teams', 'microstrategy', 'mlr', 'monday.com', 'mongo', 'mongodb', 'ms access', 'mxnet', 'mysql', 'neo4j', 'next.js', 'nltk', 'no-sql', 'node', 'node.js', 'nosql', 'notion', 'npm', 'numpy', 'objective-c', 'opencv', 'openstack', 'oracle', 'outlook', 'pandas', 'pascal', 'perl', 'phoenix', 'php', 'planner', 'plotly', 'postgresql', 'power bi', 'powerpoint', 'powershell', 'pulumi', 'puppet', 'pyspark', 'python', 'pytorch', 'qlik', 'qt', 'r', 'react', 'react.js', 'redhat', 'redis', 'redshift', 'ringcentral', 'rshiny', 'ruby', 'ruby on rails', 'rust', 'sap', 'sas', 'sass', 'scala', 'scikit-learn', 'seaborn', 'selenium', 'sharepoint', 'sheets', 'shell', 'slack', 'smartsheet', 'snowflake', 'solidity', 'spark', 'splunk', 'spreadsheet', 'spring', 'spss', 'sql', 'sql server', 'sqlite', 'ssis', 'ssrs', 'suse', 'svelte', 'svn', 'swift', 'symphony', 't-sql', 'tableau', 'tensorflow', 'terminal', 'terraform', 'theano', 'tidyverse', 'trello', 'twilio', 'typescript', 'ubuntu', 'unify', 'unity', 'unix', 'unreal', 'vb.net', 'vba', 'visio', 'visual basic', 'vmware', 'vue', 'vue.js', 'watson', 'webex', 'windows', 'wire', 'word', 'workfront', 'wrike', 'xamarin', 'yarn', 'zoom']

In [128]:
print(len(skillset_set))

219

##Filter

In [129]:
df[df.job_title_short == "Data Analyst"]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
12,Data Analyst,Stagiaire Data Analyst (H/F) - Lyon (69006),"Lyon, France",via Jobijoba,Full-time and Internship,False,France,2023-12-22 13:24:41,False,False,France,None,NaN,NaN,Engie,"['sql', 'php', 'excel', 'power bi', 'sap', 'ji...","{'analyst_tools': ['excel', 'power bi', 'sap']..."
18,Data Analyst,Data Analyst,"Warsaw, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-10-16 13:36:54,False,False,Poland,None,NaN,NaN,Glovo,"['sql', 'python', 'r', 'redshift', 'pandas', '...","{'analyst_tools': ['excel', 'looker', 'tableau..."
31,Data Analyst,Stage - Data Analyst F/H,"Paris, France",via LinkedIn,Full-time and Internship,False,France,2023-10-19 13:59:31,False,False,France,None,NaN,NaN,GROUPE BON MARCHÉ : Le Bon Marché Rive Gauche ...,['sql'],{'programming': ['sql']}
34,Data Analyst,Data Analyst als Marketing Manager Automation ...,"Erlangen, Germany",via Central Illinois Proud Jobs,Full-time,False,Germany,2023-02-23 13:31:28,True,False,Germany,None,NaN,NaN,DEFACTO GmbH,['sap'],{'analyst_tools': ['sap']}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,None,NaN,NaN,Axelon Services Corporation,None,None
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,None,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
785715,Data Analyst,Amul Careers 2023 - Apply Online - Data Analys...,India,melalui Jobsleworld - Jobs In India - Job Vaca...,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,None,NaN,NaN,Amul,None,None
785717,Data Analyst,Data & Analytics Architect (w/m/x),"Erfurt, Jerman",melalui LinkedIn,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,NTT DATA DACH,"['aws', 'azure']","{'cloud': ['aws', 'azure']}"
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."

Operadores para agregar condiciones

- usa ()
Los operadores son bitwise (&, |, ^) (and, or, xor)

In [130]:
df[(df.job_title_short == "Data Analyst") & (df.salary_year_avg > 100000)]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
410,Data Analyst,IT Business Lead Data Analyst - VP - Hybrid,"Atlantic Beach, FL",via ComputerJobs.com,Full-time,False,Georgia,2023-01-10 13:59:02,False,False,United States,year,133285.0,NaN,Citi,"['sql', 'word', 'excel', 'visio', 'powerpoint'...","{'analyst_tools': ['word', 'excel', 'visio', '..."
1555,Data Analyst,Data Analyst/Engineer (M/F/D),"Aveiro, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-04-25 13:27:25,False,False,Portugal,year,111175.0,NaN,Bosch Group,"['databricks', 'spark']","{'cloud': ['databricks'], 'libraries': ['spark']}"
1681,Data Analyst,Data Analyst,"Irvine, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-03-23 13:01:14,False,True,United States,year,111175.0,NaN,Western Digital,"['sql', 'tableau', 'power bi', 'excel']","{'analyst_tools': ['tableau', 'power bi', 'exc..."
1684,Data Analyst,Data Analyst - Data17829,"Tampa, FL",via Indeed,Full-time,False,"Florida, United States",2023-07-18 13:02:09,True,True,United States,year,120000.0,NaN,Acrisure,"['shell', 'sql', 'azure', 'databricks', 'linux']","{'cloud': ['azure', 'databricks'], 'os': ['lin..."
1867,Data Analyst,Data Integration Analyst (West Coast/Chicago),"Chicago, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-07-18 13:01:47,False,False,United States,year,101500.0,NaN,Forsta,"['php', 'python', 'express']","{'programming': ['php', 'python'], 'webframewo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783588,Data Analyst,Data Analytics Manager,"Chicago, IL",via Ladders,Full-time,False,"Illinois, United States",2023-01-09 06:01:18,False,False,United States,year,125000.0,NaN,"United Air Lines, Inc","['sql', 'r', 'python', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
783866,Data Analyst,Lead Credit Bureau Data Analyst,"Des Plaines, IL",via Ladders,Full-time,False,"Illinois, United States",2023-06-02 06:02:06,False,True,United States,year,115000.0,NaN,Discover Financial Services,['unix'],{'os': ['unix']}
784033,Data Analyst,Recruitment Data Analyst,"Mumbai, Maharashtra, India",via Ai-Jobs.net,Full-time,False,India,2023-06-07 06:10:15,False,False,India,year,111175.0,NaN,Framestore,"['power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau']}"
785187,Data Analyst,Data Analyst,"Lisbon, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-06-07 06:30:33,False,False,Portugal,year,111175.0,NaN,Farfetch,"['sql', 'python', 'r', 'looker']","{'analyst_tools': ['looker'], 'programming': [..."
785515,Data Analyst,Data Analyst,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-09-01 06:17:34,False,False,India,year,105000.0,NaN,Myntra,None,None

# Puedes usar notna()

In [131]:
df[(df.job_title_short == "Data Analyst") & (df.salary_year_avg.notna())]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
180,Data Analyst,Data Analyst III,"Dos Palos, CA",via My ArkLaMiss Jobs,Full-time,False,"California, United States",2023-02-27 13:00:39,False,True,United States,year,90250.0,NaN,California Health & Wellness,"['excel', 'powerpoint']","{'analyst_tools': ['excel', 'powerpoint']}"
410,Data Analyst,IT Business Lead Data Analyst - VP - Hybrid,"Atlantic Beach, FL",via ComputerJobs.com,Full-time,False,Georgia,2023-01-10 13:59:02,False,False,United States,year,133285.0,NaN,Citi,"['sql', 'word', 'excel', 'visio', 'powerpoint'...","{'analyst_tools': ['word', 'excel', 'visio', '..."
988,Data Analyst,DATA ANALYST (ONSITE),"Springfield, MA",via Indeed,Full-time,False,"New York, United States",2023-11-21 13:00:13,False,False,United States,year,62623.0,NaN,Springfield Public Schools,"['sql', 'excel', 'tableau']","{'analyst_tools': ['excel', 'tableau'], 'progr..."
1413,Data Analyst,Junior BI Developer,"Atlanta, GA",via Ai-Jobs.net,Full-time,False,Georgia,2023-10-31 13:57:41,False,True,United States,year,71300.0,NaN,Guidehouse,"['sql', 'excel', 'power bi']","{'analyst_tools': ['excel', 'power bi'], 'prog..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784033,Data Analyst,Recruitment Data Analyst,"Mumbai, Maharashtra, India",via Ai-Jobs.net,Full-time,False,India,2023-06-07 06:10:15,False,False,India,year,111175.0,NaN,Framestore,"['power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau']}"
784423,Data Analyst,Sales Data Analyst,"Juriquilla, Qro., Mexico",via Ai-Jobs.net,Full-time,False,Mexico,2023-01-05 06:43:20,False,False,Mexico,year,80850.0,NaN,Charger Logistics Inc,"['tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi']}"
784882,Data Analyst,Merchandising Analyst (Data Analyst),"Denton, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-04 15:29:24,False,False,United States,year,87500.0,NaN,Insight Global,"['sql', 'vba', 'tableau', 'excel', 'alteryx']","{'analyst_tools': ['tableau', 'excel', 'altery..."
785187,Data Analyst,Data Analyst,"Lisbon, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-06-07 06:30:33,False,False,Portugal,year,111175.0,NaN,Farfetch,"['sql', 'python', 'r', 'looker']","{'analyst_tools': ['looker'], 'programming': [..."
785515,Data Analyst,Data Analyst,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-09-01 06:17:34,False,False,India,year,105000.0,NaN,Myntra,None,None